{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
{{- end }}
